version: '3'
services: 
    app: 
        container_name: docker-node-mongo
        restart: always
        build: .
        environment:
            - MONGODB_URI=mongodb://mongo:27017/nest-cars
            - PORT=3003
        ports: 
            - '80:3003'
        links:
            - mongo
    mongo:
       container_name: mongo
       image: mongo
       ports: 
            - '27017:27017'
